Introduce sighash streamer (#361)
* Introduce sighash streamer

* Add timeout tx signing

* Verify timeout tx sigs

* Save timeout tx sigs to db

* Beautify nonce gen

* Fix compilation errors, caused by the merge.

* database: Add get_timeout_tx_sigs and test for timeout_tx_sigs.

* database: Serialize signatures inside of save_timeout_tx_sigs, not outside.

* clippy: Apply new suggestions.

* builder: Remove blank spaces in sighash.

* database: Write Schnorr signatures as bytea.

* aggregator: Move create_nonce_streams to rpc crate.

* cargo: Move new deps to workspace cargo file.

* rpc: Replace deprecated pin_mut with std::pin.

* error: Change message for TonicError type.

* rpc: Move extract_pub_nonce outside of function and update it's comment.

* rpc: verifier: Code simplification.

* database: Add SignaturesDB wrapper.

---------

Co-authored-by: Ceyhun Şen <ceyhuusen@gmail.com>