Unit tests for where the code coverage is not present (#307)
* actor: Remove old code and add unit tests that checks SinglePlusAnyoneCanPay scenarios.

* actor: Apply clippy suggestion.

* extended_rpc: Remove unused code.

* script_builder: Remove unused functions.

* transaction_builder: Remove unused struct.

* user: Remove unused function.

* database: Remove unused deref's.

* errors: Remove unused conversions.

* error: Remove unused InvalidPeriodError.

* utils: Remove parse_hex_to_btc_tx.

* database: Remove unused code and refactor.

* database: Remove unused tests.

* operator: Remove set_funding_utxo_rpc.

* verifier: transaction_builder fix.

* verıfıer: Add verifier_new_public_key_check.

* config: Update test error checking.

* database: wrapper: Add unit tests (no decode check).

* database: wrapper: Apply clippy suggestions.

* verifier: Add new_deposit_nonce_checks test.

* operator: Add test for set_funding_utxo.

* operator: Add rpc endpoints for set_funding_utxo.

* operator: Add rpc test for set_funding_utxo.

* actor: Rename sign_taproot_script_spend_tx.

* operator: Fix compilation errors.

* user: Re add deposit_tx.

* Change check fix

* user: Re-add deposit_tx with small refactor + unit test.

* operator: Add todo comment for set_funding_utxo_rpc test.

---------

Co-authored-by: ozankaymak <ozan.kaymak@boun.edu.tr>