General test additions/overhaul (#309)
* tests: Move common deposit operations to their own module.

* tests: deposit: Refactor a bit.

* tests: deposit: Refactor verifier parts for deposit_with_retry_checks.

* tests: deposit: format.

* verifier: Move db pub_nonces check before other operations.

* Unit tests for where the code coverage is not present (#307)

* actor: Remove old code and add unit tests that checks SinglePlusAnyoneCanPay scenarios.

* actor: Apply clippy suggestion.

* extended_rpc: Remove unused code.

* script_builder: Remove unused functions.

* transaction_builder: Remove unused struct.

* user: Remove unused function.

* database: Remove unused deref's.

* errors: Remove unused conversions.

* error: Remove unused InvalidPeriodError.

* utils: Remove parse_hex_to_btc_tx.

* database: Remove unused code and refactor.

* database: Remove unused tests.

* operator: Remove set_funding_utxo_rpc.

* verifier: transaction_builder fix.

* verıfıer: Add verifier_new_public_key_check.

* config: Update test error checking.

* database: wrapper: Add unit tests (no decode check).

* database: wrapper: Apply clippy suggestions.

* verifier: Add new_deposit_nonce_checks test.

* operator: Add test for set_funding_utxo.

* operator: Add rpc endpoints for set_funding_utxo.

* operator: Add rpc test for set_funding_utxo.

* actor: Rename sign_taproot_script_spend_tx.

* operator: Fix compilation errors.

* user: Re add deposit_tx.

* Change check fix

* user: Re-add deposit_tx with small refactor + unit test.

* operator: Add todo comment for set_funding_utxo_rpc test.

---------

Co-authored-by: ozankaymak <ozan.kaymak@boun.edu.tr>

* cargo: Update core to 0.2.0. (#311)

* tests: Move test_deposit tests/common.

* tests: Code beautification.

* user: Add documentation to generate_withdrawal_sig.

* operator: Refactor set_funding_utxo and add unit test for it.

* operator: Add doc comment for new_withdrawal_sig and white space fixes.

* tests: flow: Refactor.

* cargo: Remove debug flags and add release flags. (#312)

* fmt

* operator: Remove tracing::instrument for is_profitable.

* tests: Move run_multiple_deposits test to it's own module.

* tests: flow: Add errer type check for withdrawal_fee_too_low.

* operator: Message creation with from_digest.

* operator: Rename new_withdrawal_sig to new_signed_withdrawal.

* user: Rename generate_withdrawal_sig to generate_signed_withdrawal_transaction.

* operator: rpc: Rename new_withdrawal_sig_rpc to new_signed_withdrawal.

* operator: Small updates for Citrea check in withdrawal_proved_on_citrea.

* tests: flow: Refactors.

* tests: musig2: Add
fn get_verifiers_keypairs_and_untweaked_xonly_pk and get_nonces.

* tests: musig2: Renamings.

* tx_builder: Use match instead of if in create_taproot_address.

* tx_builder: Add test for create_taproot_address.

* script_builder: Remove tracing::instruments.

* tx_builder: Add function docs to address builders.

* tests: musig2: Renamings and whitespace removals.

* tests: taproot: Update basic test.

* tx_builder: Apply clippy suggestions.

* operator: Remove old code from withdrawal_proved_on_citrea.

* operator: Redo previous renamings.

* tx_builder: Redo changes in create_taproot_address.

* operator: Remove unnecessary clone.

* tx_builder: Rename create_move_tx to create_move_tx_handler and create new create_move_tx.

* tx_builder: Use the new create_move_tx in various places.

* tx_builder: Add basic create_move_tx test.

* general: Don't pass &XOnlyPublicKey; It supports Copy and Clone traits.

* evm_address: Don't pass &; It supports Copy and Clone traits.

* operator: Use create_move_tx.

* tx_builder: Use create_move_tx.

* tx_builder: Rename nofn_xonly_pk.

* verifier: Revert db tx improvement in new_deposit.

---------

Co-authored-by: ozankaymak <ozan.kaymak@boun.edu.tr>